default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

#development:
#  <<: *default
#  adapter: postgresql
#  encoding: unicode
#  host: db
#  username: postgres
#  password:
#  database: sample_rails_app_db

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

